package hu.infokristaly.archiwar.back.domain;

import javax.persistence.Basic;

// Generated 2012.09.26. 11:18:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import hu.infokristaly.archiwar.front.annotations.EntityInfo;

/**
 * Clerk generated by hbm2java
 */
@Entity
@Table(name = "Clerk", schema = "public")
public class Clerk implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 4103231713043595259L;
    private Long id;
    @EntityInfo(info="E-mail address", weight=2, editor="input")
    private String osUserName;
    @EntityInfo(info="User name", weight=1, editor="input")
    private String userName;
    private String vCard;
    private byte[] photo;
    private String sqlserverloginname;
    private Usergroup usergroup;
    @EntityInfo(info="Password", weight=3, editor="password")
    private String osUserPassword;
    @EntityInfo(info="Enabled", weight=4, editor="booleancheckbox")
    private Boolean enabled;

    public Clerk() {
    }

    public Clerk(Long id) {
        this.id = id;
    }

    public Clerk(Long id, String userName, String osUserName, String vCard, byte[] photo, String sqlserverloginname, Usergroup usergroup) {
        this.id = id;
        this.userName = userName;
        this.osUserName = osUserName;
        this.vCard = vCard;
        this.photo = photo;
        this.sqlserverloginname = sqlserverloginname;
        this.usergroup = usergroup;
    }

    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "clerkid", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Basic
    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "osusername", length = 128)
    public String getOsUserName() {
        return this.osUserName;
    }

    public void setOsUserName(String osusername) {
        this.osUserName = osusername;
    }

    @Column(name = "vcard")
    @Lob
    public String getVCard() {
        return this.vCard;
    }
    
    public void setVCard(String vCard) {
    	this.vCard = vCard;
    }


    @Column(name = "photo")
    @Lob
    public byte[] getPhoto() {
        return this.photo;
    }

    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    @Column(name = "sqlserverloginname", length = 50)
    public String getSqlserverloginname() {
        return this.sqlserverloginname;
    }

    public void setSqlserverloginname(String sqlserverloginname) {
        this.sqlserverloginname = sqlserverloginname;
    }

    @ManyToOne
    @JoinColumn(name = "usergroup")
    public Usergroup getUsergroup() {
        return this.usergroup;
    }

    public void setUsergroup(Usergroup usergroup) {
        this.usergroup = usergroup;
    }

    @Column(name = "osuser_password")
    public String getOsUserPassword() {
		return osUserPassword;
	}

	public void setOsUserPassword(String osUserPassword) {
		this.osUserPassword = osUserPassword;
	}

	@Column(name = "enabled")
	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}
	
	

}
